apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kafka2s3.fullname" . }}-scripts
  labels:
    app: {{ template "kafka2s3.name" . }}
    chart: {{ template "kafka2s3.chart" . }}
    heritage: {{ .Release.Service }}
data:
  k2s3.py: |
{{ tpl (.Files.Get "scripts/k2s3.py") . | indent 4 }}
